import type { Metadata } from "next";
import localFont from "next/font/local";
import "./styles/globals.css";
import { Toaster } from "sonner";

const PPNeubitFont = localFont({
	src: "../public/fonts/PPNeueBit-Bold.otf",
});

export const metadata: Metadata = {
	title: "Protoshop",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${PPNeubitFont} ${PPNeubitFont} antialiased bg-zinc-950`}>
				{children}
				<Toaster />
			</body>
		</html>
	);
}
